spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:devlog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
devlog:
  jwt-key: "drCzhdmlM81fPyQDwGEZ476mByd81azLp7jd189LQ2A="