### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "Michael",
  "email": "devlog@dev.com",
  "password": "1234"
}

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "devlog@dev.com",
  "password": "1234"
}

### 사용자페이지 조회
GET http://localhost:8080/user

### 관리자페이지 조회
GET http://localhost:8080/admin

### 메인페이지 조회
GET http://localhost:8080